sudo: required
services:
  - docker

before_install:
  - docker build -t theoppermanian/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true theoppermanian/docker-react npm run test -- --coverage

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-078663776303"
  bucket_path: "docker-react"
  access_key_id: 
    secure: "$AWS_ACCESS_KEY_ID"
  secret_access_key:
    secure: "$AWS_SECRET_ACCESS_KEY"
  on:
    branch: master
